// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var biographyTemplate, contactTemplate, main, portfolioTemplate, setActive;
    setActive = function(lnk) {
      lnk = $(lnk);
      $('#header-navlinks').children().removeClass('active');
      return lnk.parent().addClass('active');
    };
    biographyTemplate = Handlebars.compile($("#biography-template").html());
    portfolioTemplate = Handlebars.compile($("#portfolio-template").html());
    contactTemplate = Handlebars.compile($("#contact-template").html());
    main = $('#main');
    main.html(biographyTemplate);
    $('#header-navlinks').on('click', '#biography-link', function(e) {
      e.preventDefault();
      console.log('hi bio');
      main.html(biographyTemplate());
      return setActive('#biography-link');
    });
    $('#header-navlinks').on('click', '#portfolio-link', function(e) {
      e.preventDefault();
      console.log('hi port');
      main.html(portfolioTemplate());
      return setActive('#portfolio-link');
    });
    return $('#header-navlinks').on('click', '#contact-link', function(e) {
      e.preventDefault();
      console.log('hi cont');
      main.html(contactTemplate());
      return setActive('#contact-link');
    });
  });

}).call(this);

//# sourceMappingURL=main.map
