// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var setActive, unsetActive;
    unsetActive = function() {
      return $('#header-navlinks').children().removeClass('active');
    };
    setActive = function(lnk) {
      lnk = $(lnk);
      unsetActive();
      return lnk.addClass('active');
    };
    return $('#header-navlinks li').on('click', function(e) {
      var newTab, otherTabs, _i, _len, _ref;
      e.preventDefault();
      setActive(this);
      newTab = '#' + e.target.id.replace('-link', '');
      _ref = ['#biography', '#skillset', '#portfolio', '#contact'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        otherTabs = _ref[_i];
        $(otherTabs).hide();
      }
      return $(newTab).show();
    });
  });

}).call(this);

//# sourceMappingURL=main.map
